//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balakin.VSOutputEnhancer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Balakin.VSOutputEnhancer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Build error message.
        /// </summary>
        internal static string FormatDisplayName_BuildMessageError {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Build warning message.
        /// </summary>
        internal static string FormatDisplayName_BuildMessageWarning {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildMessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Build failed.
        /// </summary>
        internal static string FormatDisplayName_BuildResultFailed {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Build succeeded.
        /// </summary>
        internal static string FormatDisplayName_BuildResultSucceeded {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildResultSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Debug exception message.
        /// </summary>
        internal static string FormatDisplayName_DebugException {
            get {
                return ResourceManager.GetString("FormatDisplayName_DebugException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Trace error message.
        /// </summary>
        internal static string FormatDisplayName_DebugTraceError {
            get {
                return ResourceManager.GetString("FormatDisplayName_DebugTraceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Trace warning message.
        /// </summary>
        internal static string FormatDisplayName_DebugTraceWarning {
            get {
                return ResourceManager.GetString("FormatDisplayName_DebugTraceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Publish failed.
        /// </summary>
        internal static string FormatDisplayName_PublishResultFailed {
            get {
                return ResourceManager.GetString("FormatDisplayName_PublishResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output enhancer: Publish succeeded.
        /// </summary>
        internal static string FormatDisplayName_PublishResultSucceeded {
            get {
                return ResourceManager.GetString("FormatDisplayName_PublishResultSucceeded", resourceCulture);
            }
        }
    }
}
