//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balakin.VSOutputEnhancer {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Balakin.VSOutputEnhancer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FormatDisplayName_BowerMessageError {
            get {
                return ResourceManager.GetString("FormatDisplayName_BowerMessageError", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_BuildMessageError {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildMessageError", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_BuildMessageWarning {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildMessageWarning", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_BuildResultFailed {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildResultFailed", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_BuildResultSucceeded {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildResultSucceeded", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_BuildActionStartedSuccess {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildActionStartedSuccess", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_BuildActionStartedWarning {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildActionStartedWarning", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_BuildActionStartedError {
            get {
                return ResourceManager.GetString("FormatDisplayName_BuildActionStartedError", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_DebugException {
            get {
                return ResourceManager.GetString("FormatDisplayName_DebugException", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_DebugTraceError {
            get {
                return ResourceManager.GetString("FormatDisplayName_DebugTraceError", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_DebugTraceWarning {
            get {
                return ResourceManager.GetString("FormatDisplayName_DebugTraceWarning", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_NpmMessageError {
            get {
                return ResourceManager.GetString("FormatDisplayName_NpmMessageError", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_NpmMessageWarning {
            get {
                return ResourceManager.GetString("FormatDisplayName_NpmMessageWarning", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_NpmResultFailed {
            get {
                return ResourceManager.GetString("FormatDisplayName_NpmResultFailed", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_NpmResultSucceeded {
            get {
                return ResourceManager.GetString("FormatDisplayName_NpmResultSucceeded", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_PublishResultFailed {
            get {
                return ResourceManager.GetString("FormatDisplayName_PublishResultFailed", resourceCulture);
            }
        }
        
        public static string FormatDisplayName_PublishResultSucceeded {
            get {
                return ResourceManager.GetString("FormatDisplayName_PublishResultSucceeded", resourceCulture);
            }
        }
    }
}
